

self.addEventListener('install', event => {
  
  event.waitUntil(
    caches.open("hci-cache").then(cache => {
      return cache.addAll([
        "/",
        "/HTML/welcomepage.html",
        "CSS/login.css",
        "/HTML/login.html",
        "/HTML/Dashboard_Librarian.html",
        "/HTML/admin_menu.html",
        "/HTML/cataloging.html",
        "/Media/logo.png",
        "/CSS/admin_menu.css",
        "/CSS/checkout.css",
        "/CSS/Dashboard_Librarian.css",
        "/CSS/librarian_cataloge.css",
        "CSS/managerequest.css",
        "CSS/Members_llibrarian.css",
        "CSS/user.css",
        "CSS/usr_dashbord.css",
        "HTML/checkout.html",
        "HTML/Dashboard_admin.html",
        "HTML/help_admin.html",
        "HTML/help.html",
        "HTML/librarian_cataloge.html",
        "HTML/Librarian_manage.html",
        "HTML/Librarian_settings.html",
        "HTML/librarians.html",
        "HTML/managerequest.html",
        "HTML/Members_llibrarian.html",
        "HTML/mybooks.html",
        "HTML/RequestaNewBook.html",
        "HTML/setting.html",
        "HTML/user_dashbord.html",
        "/HTML/user.html",
        "/HTML/Users.html",
        "JAVA/admin_menu.js",
        "JAVA/checkout.js",
        "JAVA/Dashboard_Librarian.js",
        "JAVA/librarian_cataloge.js",
        "JAVA/login.js",
        "JAVA/managerequest copy.js",
        "JAVA/managerequest.js",
        "JAVA/Members_llibrarian.js",
        "JAVA/uesr.json",
        "JAVA/user_dashbord.js",
        "JAVA/user.js",
        "Media/a1.png",
        "Media/a2.png",
        "Media/a3.png",
        "Media/a4.png",
        "Media/a5.png",
        "Media/a6.png",
        "Media/a7.png",
        "Media/a8.png",
        "Media/a9.png",
        "Media/a10.png",
        "Media/a11.png",
        "Media/a12.png",
        "Media/a13.png",
        "Media/a14.png",
        "Media/a15.png",
        "Media/a16.png",
        "Media/a17.png",
        "Media/a18.png",
        "Media/a19.png",
        "Media/a20.png",
        "Media/a21.png",
        "Media/avatar.png",
        "Media/b1.jpg",
        "Media/b2.jpg",
        "Media/b3.jpg",
        "Media/b4.jpg",
        "Media/b5.jpg",
        "Media/b6.jpg",
        "Media/b7.jpg",
        "Media/b8_.jpg",
        "Media/b9.jpg",
        "Media/b10.jpg",
        "Media/b11_.jpg",
        "Media/b12.jpg",
        "Media/b13.jpeg",
        "Media/b14.jpeg",
        "Media/b15.jpg",
        "Media/b16.jpg",
        "Media/b17.jpg",
        "Media/b18.jpg",
        "Media/b19.jpg",
        "Media/b20.jpg",
        "Media/b21.jpg",
        "Media/b22.jpg",
        "Media/b23.png",
        "Media/b24.jpg",
        "Media/b25.jpg",
        "Media/b26.jpg",
        "Media/b27.jpg",
        "Media/dash1.png",
        "Media/dash2.png",
        "Media/dash3.png",
        "Media/dash4.png",
        "Media/eye.png",
        "Media/fb.png",
        "Media/Frame 16 (1).png",
        "Media/Frame 16 (2).png",
        "Media/Frame 16.png",
        "Media/Frame 311.png",
        "Media/Frame 313 (1).png",
        "Media/Frame 313.png",
        "Media/G.png",
        "Media/Group.png",
        "Media/icon-park_email-block.png",
        "Media/Illustration_welcom.png",
        "Media/Illustration.png",
        "Media/image 13 (1).png",
        "Media/image 13 (2).png",
        "Media/image 13 (3).png",
        "Media/image 13.png",
        "Media/key-solid.svg",
        "Media/L_avatar.png",
        "Media/logo-144.png",
        "Media/logo-192.png",
        
        "Media/logos_facebook.png",
        "Media/logos_twitter.png",
        "Media/profile.png",
        "Media/Rectangle 2 (1).png",
        "Media/Rectangle 2 (2).png",
        "Media/Rectangle 2 (3).png",
        "Media/Rectangle 2.png",
        "Media/Rectangle 4 (1).png",
        "Media/Rectangle 4 (2).png",
        "Media/Rectangle 4 (3).png",
        "Media/Rectangle 4.png",
        "Media/Rectangle 5 (1).png",
        "Media/Rectangle 5 (2).png",
        "Media/Rectangle 5 (3).png",
        "Media/Rectangle 5.png",
        "Media/Rectangle 24.png",
        "Media/unsplash_0Zx1bDv5BNY.png",
        "Media/unsplash_9UVmlIb0wJU.png",
        "Media/unsplash_HH4WBGNyltc.png",
        "Media/unsplash_iFgRcqHznqg.png",
        "Media/unsplash_jFAG_ixCrsM.png",
        "Media/Vector.png",
        "Media/unsplash_WNoLnJo7tS8.png"

      ]);
    })
  );
});

self.addEventListener('fetch', event => {
  event.respondWith(
    caches.match(event.request).then(response => {
      return response || fetch(event.request);
    })
  );
});




